-- -----------------------------------------------------
-- Table `DEFAULT_COMPLEX_OBJTABLE`
-- -----------------------------------------------------
USE `TARGET_SCHEMA`;
DROP TABLE IF EXISTS `DEFAULT_COMPLEX_OBJTABLE` ;

CREATE TABLE IF NOT EXISTS `DEFAULT_COMPLEX_OBJTABLE` (
  `tid` VARCHAR(30) NOT NULL DEFAULT 'TID-NOTDEF',
  `bid` VARCHAR(50) UNIQUE NOT NULL DEFAULT 'BID-NOTDEF',
  `version` INT NOT NULL DEFAULT 0,
  `revision` INT NOT NULL DEFAULT 0,
  `stitle` VARCHAR(30) NOT NULL DEFAULT 'Short Title not defined',
  `ltitle` VARCHAR(100) NOT NULL DEFAULT 'Long Title not defined',
  `comment` TEXT NULL DEFAULT NULL,
  `cuser` VARCHAR(100) NOT NULL,
  `ctime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `uuser` VARCHAR(100) NULL DEFAULT NULL,
  `utime` TIMESTAMP NULL DEFAULT NULL,
  `isActive` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`tid`),
  CONSTRAINT `FK_DEFCOMPOBJ_USER_CUSER`
    FOREIGN KEY (`cuser`)
    REFERENCES `CORE_USER_ACCOUNTS` (`tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DEFCOMPOBJ_USER_UUSER`
    FOREIGN KEY (`uuser`)
    REFERENCES `CORE_USER_ACCOUNTS` (`tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'DEFAULT_COMPLEX_OBJECT_COMMENT';

CREATE UNIQUE INDEX `UQ_BID-VER-REV` ON `DEFAULT_COMPLEX_OBJTABLE` (`bid` ASC, `version` ASC, `revision` ASC);
CREATE INDEX `FK_DEFCOMPOBJ_USER_CUSER_idx` ON `DEFAULT_COMPLEX_OBJTABLE` (`cuser` ASC);
CREATE INDEX `FK_DEFCOMPOBJ_USER_UUSER_idx` ON `DEFAULT_COMPLEX_OBJTABLE` (`uuser` ASC);

-- -----------------------------------------------------------------------------
-- TRIGGERS
-- -----------------------------------------------------------------------------
DELIMITER $$

USE `TARGET_SCHEMA`$$
DROP TRIGGER IF EXISTS `TRIG_BEFINSERT_DEFAULT_COMPLEX_OBJTABLE` $$
USE `TARGET_SCHEMA`$$
CREATE DEFINER = CURRENT_USER TRIGGER TRIG_BEFINSERT_DEFAULT_COMPLEX_OBJTABLE BEFORE INSERT ON DEFAULT_COMPLEX_OBJTABLE FOR EACH ROW
BEGIN

	DECLARE lStrNewTID VARCHAR(30);
  SELECT CORE_GenNewTIDForTable('DEFAULT_COMPLEX_OBJTABLE') INTO lStrNewTID ;
	SET NEW.tid = lStrNewTID;
  SET NEW.bid = lStrNewTID;
	SET NEW.CUSER = CURRENT_USER;
END$$


USE `TARGET_SCHEMA`$$
DROP TRIGGER IF EXISTS `TRIG_AFTINSERT_DEFAULT_COMPLEX_OBJTABLE` $$
USE `TARGET_SCHEMA`$$
CREATE DEFINER = CURRENT_USER TRIGGER TRIG_AFTINSERT_DEFAULT_COMPLEX_OBJTABLE AFTER INSERT ON DEFAULT_COMPLEX_OBJTABLE FOR EACH ROW
BEGIN
	CALL LOGS_LogDataEvent_Insert(NEW.tid);
    CALL CORE_RegisterNewTID(NEW.tid,'DEFAULT_COMPLEX_OBJTABLE');
END$$


USE `TARGET_SCHEMA`$$
DROP TRIGGER IF EXISTS `TRIG_BEFUPDATE_DEFAULT_COMPLEX_OBJTABLE` $$
USE `TARGET_SCHEMA`$$
CREATE DEFINER = CURRENT_USER TRIGGER TRIG_BEFUPDATE_DEFAULT_COMPLEX_OBJTABLE BEFORE UPDATE ON DEFAULT_COMPLEX_OBJTABLE FOR EACH ROW
BEGIN
	SET NEW.uuser = CURRENT_USER;
    SET NEW.utime = NOW();
END$$


USE `TARGET_SCHEMA`$$
DROP TRIGGER IF EXISTS `TRIG_AFTUPDATE_DEFAULT_COMPLEX_OBJTABLE` $$
USE `TARGET_SCHEMA`$$
CREATE DEFINER = CURRENT_USER TRIGGER TRIG_AFTUPDATE_DEFAULT_COMPLEX_OBJTABLE AFTER UPDATE ON DEFAULT_COMPLEX_OBJTABLE FOR EACH ROW
BEGIN
	CALL LOGS_LogDataEvent_Update(NEW.tid);
END$$

DELIMITER ;

-- -----------------------------------------------------------------------------
-- TODO reviseComplexObject & versionObject
-- -----------------------------------------------------------------------------

-- -----------------------------------------------------------------------------
-- Intégration à la configuration du CORE
-- -----------------------------------------------------------------------------
INSERT INTO `CORE_TYPEOBJECTS` (
 `stitle`,
 `ltitle`,
 `comment`,
 `obj_type`,
 `obj_prefix`,
 `obj_tablename`,
 `isSystem`)
VALUES (
 'DEFAULT_COMPLEX_OBJECT_STITLE',
 'DEFAULT_COMPLEX_OBJECT_LTITLE',
 'DEFAULT_COMPLEX_OBJECT_COMMENT',
 'Complex',
 'DEFAULT_COMPLEX_OBJECT_SIGLE',
 'DEFAULT_COMPLEX_OBJTABLE',
 0);
