-- MySQL Script generated by MySQL Workbench
-- Sat Sep  2 21:44:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myecm
-- -----------------------------------------------------
-- MyECM Application Main Database.
DROP SCHEMA IF EXISTS `myecm` ;

-- -----------------------------------------------------
-- Schema myecm
--
-- MyECM Application Main Database.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myecm` DEFAULT CHARACTER SET utf8 ;
USE `myecm` ;

-- -----------------------------------------------------
-- Table `myecm`.`APP_USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myecm`.`APP_USERS` ;

CREATE TABLE IF NOT EXISTS `myecm`.`APP_USERS` (
  `login` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(50) NULL,
  `lastname` VARCHAR(50) NULL,
  `creation_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myecm`.`CORE_TOBJV_OBJET1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myecm`.`CORE_TOBJV_OBJET1` ;

CREATE TABLE IF NOT EXISTS `myecm`.`CORE_TOBJV_OBJET1` (
  `id` INT(8) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT 'Identifiant unique géré par le SGBD.',
  `tid` VARCHAR(30) NOT NULL DEFAULT 'TID-NOTDEFINED' COMMENT 'Identifiant Unique applicatif',
  `bid` VARCHAR(100) NOT NULL DEFAULT 'BID-NOTDEFINED' COMMENT 'Identifiant \"Business\" unique.',
  `version` INT NOT NULL DEFAULT 1 COMMENT 'Version de l\'objet',
  `revision` INT NOT NULL DEFAULT 0 COMMENT 'Révision de l\'objet',
  `stitle` VARCHAR(30) NOT NULL DEFAULT 'Titre cournt non défini' COMMENT 'Titre court de l\'objet',
  `ltitle` VARCHAR(100) NOT NULL DEFAULT 'Titre long non défini' COMMENT 'Titre long de l\'objet',
  `comment` TEXT NULL DEFAULT NULL COMMENT 'description de l\'objet',
  `creator` VARCHAR(100) NOT NULL,
  `ctime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updator` VARCHAR(100) NULL DEFAULT NULL,
  `utime` TIMESTAMP NULL DEFAULT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_TID` (`tid` ASC),
  UNIQUE INDEX `UQ_BID-VERS-REV` (`bid` ASC, `version` ASC, `revision` ASC),
  INDEX `FK_TOBJ_USER_CREATOR_idx` (`creator` ASC),
  INDEX `FK_TOBJ_USER_UPDATOR_idx` (`updator` ASC),
  CONSTRAINT `FK_TOBJ_USER_CREATOR`
    FOREIGN KEY (`creator`)
    REFERENCES `myecm`.`APP_USERS` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TOBJ_USER_UPDATOR`
    FOREIGN KEY (`updator`)
    REFERENCES `myecm`.`APP_USERS` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myecm`.`CORE_TREF_DATA1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myecm`.`CORE_TREF_DATA1` ;

CREATE TABLE IF NOT EXISTS `myecm`.`CORE_TREF_DATA1` (
  `id` INT(8) ZEROFILL NOT NULL AUTO_INCREMENT COMMENT 'Identifiant unique géré par le SGBD.',
  `tid` VARCHAR(30) NOT NULL DEFAULT 'TID-NOTDEFINED' COMMENT 'Identifiant Unique applicatif',
  `bid` VARCHAR(100) NOT NULL DEFAULT 'BID-NOTDEFINED' COMMENT 'Identifiant \"Business\" unique.',
  `stitle` VARCHAR(30) NOT NULL DEFAULT 'Titre cournt non défini' COMMENT 'Titre court de l\'objet',
  `ltitle` VARCHAR(100) NOT NULL DEFAULT 'Titre long non défini' COMMENT 'Titre long de l\'objet',
  `comment` TEXT NULL DEFAULT NULL COMMENT 'description de l\'objet',
  `creator` VARCHAR(100) NOT NULL,
  `ctime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updator` VARCHAR(100) NULL DEFAULT NULL,
  `utime` TIMESTAMP NULL DEFAULT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_TID` (`tid` ASC),
  UNIQUE INDEX `UQ_BID-VERS-REV` (`bid` ASC),
  INDEX `FK_TOBJ_USER_CREATOR_idx` (`creator` ASC),
  INDEX `FK_TOBJ_USER_UPDATOR_idx` (`updator` ASC),
  CONSTRAINT `FK_TOBJ_USER_CREATOR0`
    FOREIGN KEY (`creator`)
    REFERENCES `myecm`.`APP_USERS` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TOBJ_USER_UPDATOR0`
    FOREIGN KEY (`updator`)
    REFERENCES `myecm`.`APP_USERS` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myecm`.`APP_LOGS_DATAEVENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myecm`.`APP_LOGS_DATAEVENTS` ;

CREATE TABLE IF NOT EXISTS `myecm`.`APP_LOGS_DATAEVENTS` (
  `id` INT(8) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `myecm`;

DELIMITER $$

USE `myecm`$$
DROP TRIGGER IF EXISTS `myecm`.`CORE_TOBJV_OBJET1_BEFORE_INSERT` $$
USE `myecm`$$
CREATE DEFINER = CURRENT_USER TRIGGER `myecm`.`CORE_TOBJV_OBJET1_BEFORE_INSERT` BEFORE INSERT ON `CORE_TOBJV_OBJET1` FOR EACH ROW
BEGIN
	-- UID RULE
    
    
END$$


USE `myecm`$$
DROP TRIGGER IF EXISTS `myecm`.`CORE_TOBJV_OBJET1_AFTER_INSERT` $$
USE `myecm`$$
CREATE DEFINER = CURRENT_USER TRIGGER `myecm`.`CORE_TOBJV_OBJET1_AFTER_INSERT` AFTER INSERT ON `CORE_TOBJV_OBJET1` FOR EACH ROW
BEGIN

END
$$


USE `myecm`$$
DROP TRIGGER IF EXISTS `myecm`.`CORE_TOBJV_OBJET1_BEFORE_UPDATE` $$
USE `myecm`$$
CREATE DEFINER = CURRENT_USER TRIGGER `myecm`.`CORE_TOBJV_OBJET1_BEFORE_UPDATE` BEFORE UPDATE ON `CORE_TOBJV_OBJET1` FOR EACH ROW
BEGIN

END
$$


USE `myecm`$$
DROP TRIGGER IF EXISTS `myecm`.`CORE_TOBJV_OBJET1_AFTER_UPDATE` $$
USE `myecm`$$
CREATE DEFINER = CURRENT_USER TRIGGER `myecm`.`CORE_TOBJV_OBJET1_AFTER_UPDATE` AFTER UPDATE ON `CORE_TOBJV_OBJET1` FOR EACH ROW
BEGIN

END
$$


USE `myecm`$$
DROP TRIGGER IF EXISTS `myecm`.`CORE_TOBJV_OBJET1_BEFORE_INSERT` $$
USE `myecm`$$
CREATE DEFINER = CURRENT_USER TRIGGER `myecm`.`CORE_TOBJV_OBJET1_BEFORE_INSERT` BEFORE INSERT ON `CORE_TOBJV_OBJET1` FOR EACH ROW
BEGIN
	-- UID RULE
    
    
END$$


USE `myecm`$$
DROP TRIGGER IF EXISTS `myecm`.`CORE_TOBJV_OBJET1_AFTER_INSERT` $$
USE `myecm`$$
CREATE DEFINER = CURRENT_USER TRIGGER `myecm`.`CORE_TOBJV_OBJET1_AFTER_INSERT` AFTER INSERT ON `CORE_TOBJV_OBJET1` FOR EACH ROW
BEGIN

END
$$


USE `myecm`$$
DROP TRIGGER IF EXISTS `myecm`.`CORE_TOBJV_OBJET1_BEFORE_UPDATE` $$
USE `myecm`$$
CREATE DEFINER = CURRENT_USER TRIGGER `myecm`.`CORE_TOBJV_OBJET1_BEFORE_UPDATE` BEFORE UPDATE ON `CORE_TOBJV_OBJET1` FOR EACH ROW
BEGIN

END
$$


USE `myecm`$$
DROP TRIGGER IF EXISTS `myecm`.`CORE_TOBJV_OBJET1_AFTER_UPDATE` $$
USE `myecm`$$
CREATE DEFINER = CURRENT_USER TRIGGER `myecm`.`CORE_TOBJV_OBJET1_AFTER_UPDATE` AFTER UPDATE ON `CORE_TOBJV_OBJET1` FOR EACH ROW
BEGIN

END
$$


DELIMITER ;
